apiVersion: batch/v1
kind: Job
metadata:
  name: jobintel-dr-once
  namespace: jobintel
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 3600
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ecr-pull
      containers:
        - name: jobintel
          image: 048622080012.dkr.ecr.us-east-1.amazonaws.com/jobintel:live-snapshotdir-20260205-082950
          imagePullPolicy: Always
          workingDir: /app
          command: ["python", "scripts/run_daily.py"]
          args: ["--profiles", "cs", "--us_only", "--no_post", "--snapshot-only", "--offline"]
          env:
            - name: PUBLISH_S3
              value: "0"
            - name: PUBLISH_S3_DRY_RUN
              value: "1"
          volumeMounts:
            - name: jobintel-data
              mountPath: /app/data/ashby_cache
            - name: jobintel-state
              mountPath: /app/state
      volumes:
        - name: jobintel-data
          emptyDir: {}
        - name: jobintel-state
          emptyDir: {}
